import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {expect} from '@playwright/test';
import {mkdir, writeFile} from 'node:fs/promises';
import {addDays, shanghaiDate} from '../site/lib/domain.mjs';
const base = process.env.CALENDAR_TEST_URL || 'http://127.0.0.1:4174/';
const browser = await chromium.launch({channel:'chrome',headless:true});
const context = await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
const page = await context.newPage();
let downloads = 0;
context.on('request', request => { if (new URL(request.url()).pathname.endsWith('/data/events.json')) downloads++; });
try {
  await page.goto(base);
  await expect(page.locator('#sync-meta')).toContainText('最近成功同步');
  await page.evaluate(async()=>{await navigator.serviceWorker.ready;});
  await page.waitForFunction(()=>!!navigator.serviceWorker.controller);
  const manifest = await page.evaluate(async()=> (await fetch(document.querySelector('link[rel="manifest"]').href)).json());
  assert.equal(manifest.display,'standalone');
  assert.equal(manifest.icons.length,3);
  const original = await page.evaluate(async()=> (await (await caches.open('zju-calendar-data-v1')).match(new URL('./data/events.json',location.href))).json());
  const firstDownloads = downloads;
  for (let i = 0; i < 5; i++) await page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));
  await page.reload();
  await expect(page.locator('#sync-meta')).toContainText('最近成功同步');
  assert.equal(downloads,firstDownloads,'foreground changes and reload should reuse the snapshot');
  const tomorrow = addDays(shanghaiDate(),1);
  if (!await page.locator(`[data-date="${tomorrow}"]`).count()) await page.locator('#next-week').click();
  await page.locator(`[data-date="${tomorrow}"]`).click();
  await page.locator('.favorite-button:visible').first().click();
  await expect(page.locator('#favorite-total')).toHaveText('1');
  await context.setOffline(true);
  await page.reload();
  await expect(page.locator('#sync-meta')).toContainText('最近成功同步');
  await expect(page.locator('#favorite-total')).toHaveText('1');
  await expect(page.locator('#offline-status')).toBeVisible();
  const offline = await page.evaluate(async()=>{const r=await fetch('./data/events.json?offline-test=1');return {cached:r.headers.get('X-Calendar-Cached'),body:await r.json()};});
  assert.equal(offline.cached,'1');
  assert.equal(offline.body.lastSuccessAt,original.lastSuccessAt);
  await page.locator('#tab-favorites').click();
  await expect(page.locator('.favorites-list .event-card')).toHaveCount(1);
  const evidence = new URL('../../.omo/evidence/zju/pwa/',import.meta.url);
  await mkdir(evidence,{recursive:true});
  await page.screenshot({path:new URL('offline.png',evidence).pathname.replace(/^\/(\w:)/,'$1'),fullPage:true});
  await context.setOffline(false);
  await page.reload();
  await expect(page.locator('#sync-meta')).toContainText('最近成功同步');
  await expect(page.locator('#offline-status')).toBeHidden();
  await writeFile(new URL('report.json',evidence),JSON.stringify({base,testedAt:new Date().toISOString(),result:'PASS',checks:['manifest and icons','offline reload','cached snapshot preserves timestamp','favorites survive offline restart','network restores fresh data']},null,2));
  console.log('PASS PWA: manifest, no duplicate full downloads, offline restart, cached timestamp, favorites, reconnect');
} finally {await browser.close();}
